version: "3.7"
services:
  database:
    image: postgres:15.1-alpine
    container_name: database
    command: postgres -p 5121
    expose:
      - 5121
    env_file:
      - .env_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5121"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always

  redis_ylab:
    image: redis:latest
    container_name: redis_ylab
    expose:
      - 5370
    ports:
      - "5370:5370"
    env_file:
      - .env_prod
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    env_file:
      - .env_prod
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5

  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_prod
    container_name: main_app
    command: sh -c "chmod +x /food_app/docker/migration.sh && /food_app/docker/migration.sh"
    ports:
      - "8814:8000"
    depends_on:
      database:
        condition: service_healthy
      redis_ylab:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
